Repository matt-usurp/validate-semver, pull requests merged in 2024-04, with the labels that each got.

#4 feat: upgrade to `node20` and `esm`
  .eslintrc.cjs
  Makefile
  README.md
  action.yaml
  build/action.js
  commitlint.config.cjs
  package-lock.json
  package.json
  src/core/action.test.ts
  src/core/action.ts
  src/core/action/input.test.ts
  src/core/version.test.ts
  src/core/version.ts
  src/main.ts
  tsconfig.json
Labels: enhancement

#6 fix: built action filename incorrect
  Makefile
  build/action.mjs
Labels: bug

#7 build: ensure github actions are using the correct node version
  .github/workflows/build.yaml
Labels: enhancement

#8 docs: updating `README` and cleaning up
  README.md
Labels: documentation

#9 fix: use `commonjs` on `node@20`
  .github/workflows/build.yaml
  Makefile
  action.yaml
  build/action.cjs
  package.json
  tsconfig.json
Labels: bug

#15 build: developer contributing information and configuration files
  .github/workflows/build.yaml
  .nvmrc
  CONTRIBUTING.md
Labels: documentation

#14 feat: add build info
  README.md
  build/action.cjs
  src/core/action.test.ts
  src/core/action.ts
  src/core/version.test.ts
  src/core/version.ts
Labels: bug, enhancement
